Repository ensdomains/address-encoder, pull requests merged in 2020-11, with the labels that each got.

#133 Add support for AR addresses
  README.md
  src/__tests__/index.test.ts
  src/index.ts
Labels: file size too large

#147 Add MIOTA support
  README.md
  src/__tests__/index.test.ts
  src/index.ts
Labels: under active review

#149 Add Support For TOMO Addresses In Encoding Library
  README.md
  src/__tests__/index.test.ts
  src/index.ts
Labels: insufficient reference, under active review

#146 Added AVAX support
  README.md
  src/__tests__/index.test.ts
  src/index.ts
Labels: under active review

#235 Add support for ARDR address encoding and decoding functionality
  README.md
  src/__tests__/index.test.ts
  src/index.ts
Labels: under active review

#238 Add support for GXC address encoding and deconding functionalities
  README.md
  package.json
  src/__tests__/index.test.ts
  src/index.ts
Labels: under active review

#150 Added BTS support
  README.md
  src/__tests__/index.test.ts
  src/index.ts
Labels: under active review

#127 add EWT encoder
  README.md
  src/__tests__/index.test.ts
  src/index.ts
Labels: insufficient reference, under active review

#233 Add support for Super Zero Protocol (SERO) addresses for encoding and decoding
  README.md
  src/__tests__/index.test.ts
  src/index.ts
Labels: under active review
