Repository ensdomains/address-encoder, pull requests merged in 2020-12, with the labels that each got.

#210 Add support for XMR addresses
  README.md
  src/__tests__/index.test.ts
  src/index.ts
  src/monero/xmr-base58.ts
Labels: file size too large

#152 Add support for XVG address
  README.md
  src/__tests__/index.test.ts
  src/index.ts
Labels: insufficient reference, under active review

#236 Add support for VSYS address encoding and decoding functionality
  README.md
  package-lock.json
  package.json
  src/__tests__/index.test.ts
  src/index.ts
Labels: file size too large

#231 Add WAN support
  README.md
  src/__tests__/index.test.ts
  src/index.ts
Labels: file size too large

#260 Add support for BTM addresses
  README.md
  src/__tests__/index.test.ts
  src/index.ts
Labels: under active review

#130 Added FLOW support
  README.md
  src/__tests__/index.test.ts
  src/flow/index.ts
  src/index.ts
Labels: under active review

#258 Add support for NULS addresses
  README.md
  src/__tests__/index.test.ts
  src/index.ts
Labels: under active review

#222 Add support for NEAR Protocol (NEAR) addresses
  README.md
  src/__tests__/index.test.ts
  src/index.ts
Labels: under active review

#287 Add Groestlcoin (GRS) support
  README.md
  src/@types/groestl-hash-js/index.d.ts
  src/__tests__/index.test.ts
  src/groestl-hash-js/groestl.js
  src/groestl-hash-js/helper.js
  src/groestl-hash-js/index.js
  src/groestl-hash-js/op.js
  src/index.ts
Labels: file size too large
